### ISSUE TITLE
Merge/Build Conflicts => Do Not Build Docker Image

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/CoreDataStore#106]
When Branch is Checked In Need a Way to Test if Merge Conflict Exists 

![capture](https://user-images.githubusercontent.com/887805/30004897-100a39b0-90a5-11e7-9dfd-0699fcd74cce.PNG)

https://stackoverflow.com/questions/6335717/can-git-tell-me-if-a-merge-will-conflict-without-actually-merging

- [ ] 1 - Test if merge Conflicts Exist 

![capture](https://user-images.githubusercontent.com/887805/29998936-2ec3f29c-9005-11e7-8e8a-db6736c07e33.PNG)

- [ ] 2 - Fail Build if Behind 

![behind](https://user-images.githubusercontent.com/887805/29998916-d198f446-9004-11e7-847f-7346a0725674.png)

**Comment by leduong** [comment]
Should be manually merged, avoid the rollback version of the old

**Comment by stuartshay** [comment]
I want to test if the branch will cause conflicts and fail the build

Merging will still be done manually

This will ensure that the child branches are using up to date code
