### ISSUE TITLE
Main Page Paging/Filtering/Cleanup 

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/CoreDataStore#12]
1) On the Main Page Fix Formatting  Mock-up below

- Add SASS to build 
-  jshint/csshint

Here is the working site 
http://www.nyc.gov/html/lpc/html/publications/landmark_designations.shtml

![mockup](https://cloud.githubusercontent.com/assets/887805/15764980/c40cbf66-28fd-11e6-8ba2-291abc852b24.png)

2) Implement Same Paging as other site 

- Filtering is not clearing 

![query](https://cloud.githubusercontent.com/assets/887805/16574119/6a0d2f90-4249-11e6-81b2-f75599166757.png)

![pager](https://cloud.githubusercontent.com/assets/887805/16574035/a92ca2ce-4248-11e6-9d69-b0c0ccafbb8c.png)

The Total Count is returned in the Response Header 

<pre>
  "x-inlinecount": "1622"
</pre>

![capture](https://cloud.githubusercontent.com/assets/887805/16574003/4aca9588-4248-11e6-9c80-c1f7c24f7b60.PNG)

**Comment by leduong** [comment]
![screenshot from 2016-07-19 09-08-31](https://cloud.githubusercontent.com/assets/1042749/16936389/6afa88ec-4d90-11e6-80eb-640e4c43d866.png)

**Comment by stuartshay** [comment]
Fix Paging
