### ISSUE TITLE
 Diagnostics - Tab 

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/CoreDataStore#13]
Diagnostics

Swagger API 
![capture](https://cloud.githubusercontent.com/assets/887805/16642162/066e8504-43d6-11e6-937a-396784ab8618.PNG)

The Page Needs to Refresh every 1 Sec - Used to test nginx Reverse Proxy
<pre>
 function refresh(milliseconds) { 
          setTimeout("location.reload(true);", milliseconds); 
  } 
    refresh(1000);
</pre>

**Comment by leduong** [comment]
![screenshot from 2016-08-02 21-28-50](https://cloud.githubusercontent.com/assets/1042749/17332223/2f125210-58f8-11e6-8668-d7d722357db3.png)

**Comment by zloom** [comment]
Do not use hardcoded host name. 
You can simply use this.http.get('api/diagnostics') instead of this.http.get(hostname + 'api/diagnostics').

**Comment by stuartshay** [comment]
1) Add Platform Label 
2)  Need Auto Refresh  to Show Load Balancer IP Address  

![refresh](https://cloud.githubusercontent.com/assets/887805/17426254/db1ec410-5aa3-11e6-88a8-c3ec96f07b82.png)

**Comment by stuartshay** [comment]
Can you add this code so the API Refreshes - Need to Test API 


````
 function refresh(milliseconds) { 
          setTimeout("location.reload(true);", milliseconds); 
  } 
    refresh(1000);
````

**Comment by stuartshay** [comment]
Thanks !!!!
