### ISSUE TITLE
gulp-livereload/.Net Core Reload

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/CoreDataStore#23]
Setup Gulp Live Reload or Similar
https://www.npmjs.com/package/gulp-livereload

https://jonhilton.net/2016/08/04/compile-your-changes-on-the-fly-with-net-core/

**Comment by leduong** [comment]
Hi!

It was builtin source

**Comment by stuartshay** [comment]
Can you Explain how this works,  
Just include in Documentation in ReadMe.md
