### ISSUE TITLE
Docker Container - Not loading 

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/CoreDataStore#36]
Build Container from Docker Hub
https://hub.docker.com/r/stuartshay/coredatastore/tags/

Lattest Tag is from Build

Site  does not show up

Swagger Runs 
http://40.84.59.215:5000/Swagger/UI/Index.html

````
   docker pull stuartshay/coredatastore
   docker run --rm --name <containername> -p 5000:5000 stuartshay/coredatastore
````

Docker Notes
https://github.com/stuartshay/CoreDataStore/blob/master/src/docker/README.md

**Comment by leduong** [comment]
![screenshot from 2016-08-29 16-08-20](https://cloud.githubusercontent.com/assets/1042749/18046621/ed0cb98a-6e02-11e6-91e7-3053c24e45b3.png)

**Comment by leduong** [comment]
Hi!

```bash
git clone https://github.com/stuartshay/CoreDataStore.git
cd CoreDataStore
git checkout leduong-docker
docker-compose build
docker run -d -p 5000:5000 coredatastore_web
```

**Comment by stuartshay** [comment]
Need to create a docker-compose-staging.yml

That points to the DB and Web site on Docker Hub

````
https://hub.docker.com/r/stuartshay/coredatastore-postgre/tags/

docker run --rm --name  postgresdb-stable -p 5432:5432 stuartshay/coredatastore-postgre:stable
````

**Comment by leduong** [comment]
```
docker run -d -p 5432:5432  --name coredatastore_postgresdb stuartshay/coredatastore-postgre:stable
docker run -d -p 5000:5000 --link coredatastore_postgresdb stuartshay/coredatastore
```

**Comment by stuartshay** [comment]
Works !!!
