### ISSUE TITLE
Paging - Response Header  X-InlineCount 

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/CoreDataStore#39]
Paging Total Count is Hard Coded

Total Count needs to be read from Response Header 

![inline](https://cloud.githubusercontent.com/assets/887805/22619991/748c6c22-eacf-11e6-87a1-2fade3bf4ab4.png)

**Comment by leduong** [comment]
it's done.22 days ago

**Comment by stuartshay** [comment]
Paging Broken - Select Last Record 

Clearing of the Dropdowns got Broken on Merge

See:
http://stuartshay.github.io/CoreDataStore/
