### ISSUE TITLE
Add Map on Main Page 

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/CoreDataStore#41]
Page & NavigatorMaps Can be renamed to Dashboard
- [ ]  1) Add Google Map, Map Can be the Same as NavigatorMaps  
       (No Data or API Required)

![map](https://cloud.githubusercontent.com/assets/887805/19411159/3288465a-92ca-11e6-9ea8-12ef8ebcc222.PNG)

**Comment by leduong** [comment]
![screenshot from 2016-12-12 00-32-57](https://cloud.githubusercontent.com/assets/1042749/21081890/a1eba216-c002-11e6-8731-273977da6c45.png)

**Comment by leduong** [comment]
![screenshot from 2016-12-12 00-40-18](https://cloud.githubusercontent.com/assets/1042749/21081946/9c2cb3dc-c003-11e6-97f6-7b627d1ec943.png)

**Comment by stuartshay** [comment]
See Google Sheet for API Endpoints

https://docs.google.com/spreadsheets/d/1tzdMtnpDxcOE1zUkwvEaATRmdOYD6huDRHcYOaqjmB4/edit#gid=0


![maps](https://cloud.githubusercontent.com/assets/887805/21083368/dc29edb6-bfbc-11e6-98fe-974a4bbb69e6.png)

**Comment by leduong** [comment]
![screenshot from 2016-12-12 09-28-05](https://cloud.githubusercontent.com/assets/1042749/21086255/59adcd30-c04d-11e6-806d-cd50b869055f.png)

**Comment by stuartshay** [comment]
Complete  - Need to build data for correct functionality
