### ISSUE TITLE
Landmarks Details 

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/CoreDataStore#5]
1) Click on a LPC Report should show details page 

![click](https://cloud.githubusercontent.com/assets/887805/16030717/f5f3e758-31c1-11e6-8b0f-31ffe35b9070.png)

**Details Page** 

![details](https://cloud.githubusercontent.com/assets/887805/16030680/a442f0c0-31c1-11e6-95a9-6c3479d6307c.png)

1) Bread Crumb - Should return the user to the same page in the Index

![bread](https://cloud.githubusercontent.com/assets/887805/16030742/4c78d2d2-31c2-11e6-9ddd-c188549301e9.PNG)

2) Edit  Details Saved to Database
 Server Side Validation Errors will be returned in JSON (Using Fluent Validation)

![post](https://cloud.githubusercontent.com/assets/887805/16030764/920ff370-31c2-11e6-9cb6-1fb5cd21b3a9.PNG)

PUT Request Only - No Insert 
![put](https://cloud.githubusercontent.com/assets/887805/16030858/7555193a-31c3-11e6-9a65-2131303e5bc5.PNG)

3) Paging Grid 

![get](https://cloud.githubusercontent.com/assets/887805/16030834/414db62e-31c3-11e6-8ef3-b0a9dea66abc.PNG)

<pre>
SELECT * FROM Landmark
WHERE 1 = 1  
AND LP_NUMBER = 'LP-02546'
ORDER BY BBL
</pre>

**Comment by stuartshay** [comment]
Do not hard code url or port
baseUrl: string = 'http://' + window.location.hostname + ':5000/';

**Comment by leduong** [comment]
Hi!

if you want dynamic link, you can change at here (dev/local)
https://github.com/stuartshay/CoreDataStore/blob/leduong-gulp/src/CoreDataStore.Web/gulpfile.ts#L111
