### ISSUE TITLE
LPC Details 

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/CoreDataStore#50]
- [ ] 1)  Angular Grid

http://ui-grid.info/

Basic Example - Sorting Only
![untitled](https://cloud.githubusercontent.com/assets/887805/21302332/ef8a478a-c583-11e6-8fba-9ff79d87a902.png)

### Grid Goes Below the Map

![untitled](https://cloud.githubusercontent.com/assets/887805/23576538/3ca6a734-0076-11e7-831f-e31b5fd8f94a.png)

**Comment by leduong** [comment]
![screenshot from 2017-05-17 15-02-25](https://cloud.githubusercontent.com/assets/1042749/26144119/de9644b6-3b11-11e7-9bdf-e1d13c416eab.png)

**Comment by stuartshay** [comment]
See Basic Example 
http://ui-grid.info/

Need to Display All the Records (No Paging) 
History District will have many records 

![untitled](https://cloud.githubusercontent.com/assets/887805/26260759/7025df82-3c9c-11e7-8dd2-ae1e37b06c9a.png)
