### ISSUE TITLE
LPC Details - Server Validation

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/CoreDataStore#63]
- [x] 1 - Add angular2-toaster (This was working at 1 Time
 
 - [x] 2 - Server Side Validation

There is Server Side Validation that will validate the First Text Box (Enter Less then 4 Characters)

When Saved, the JSON Returned will give a validation error message.
JSON Can be modified extra properties not needed,

![untitled](https://cloud.githubusercontent.com/assets/887805/24986139/78abdc6c-1fc6-11e7-9559-30a7aa91ebf0.png)

**Comment by leduong** [comment]
![screenshot from 2017-05-19 19-56-02](https://cloud.githubusercontent.com/assets/1042749/26248729/b44f2a8e-3ccd-11e7-8fbc-89d2eddd675b.png)
