### ISSUE TITLE
DEV/Stage/Prod - Entity Framework Config - Setup

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/CoreDataStore#7]
1)  Get Website working,  Test using Swagger Link
http://localhost:5000/swagger/ui/index.html

Site has been coded to use SQLite 

2) Run EF Migrations to Setup DB 
https://github.com/stuartshay/CoreDataStore/tree/master/test

i; Config Info Hard Coded 

<pre>
 Helpers/TemporaryDbContextFactory.cs
</pre>

ii. TODO: Add Config File in Test Project 
iii. Run Migrations 
<pre>
   dotnet ef database update
</pre>

Note: SQL Sever & Postgre  Migration will create DB 

iv. Load Data 
Repositories/LPCReportRepositoryTest.cs

Use VS Tests to Run
![tests](https://cloud.githubusercontent.com/assets/887805/16291985/dbf1e0a6-38da-11e6-8492-ecf1d6543eb8.PNG)

3) Look over Config 
https://docs.asp.net/en/latest/fundamentals/environments.html

**Comment by david-x-chen** [comment]
I cannot commit to this repo.

**Comment by stuartshay** [comment]
I will add you when I get back in 1 he
