### ISSUE TITLE
Ag-Grid - Enhancements

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/CoreDataStore#75]
Ag-Grid Enhancements 

- [ ] 1  -  Need to Select & Copy Cell Values

![cell](https://cloud.githubusercontent.com/assets/887805/26770844/40eafb32-4988-11e7-9df6-17da6ee515da.PNG)

https://www.ag-grid.com/javascript-grid-cell-editing/?framework=all#gsc.tab=0

Just Need Copy Cell 

![copy](https://cloud.githubusercontent.com/assets/887805/26771100/0441b778-498a-11e7-88fb-fe1df19fba82.PNG)

- [ ] 2  -  Scale Grid Scroll Bar

![scale](https://user-images.githubusercontent.com/887805/27100089-e9e46b2e-504a-11e7-91eb-ab124e013348.png)

**Comment by leduong** [comment]
It's still, demo is complex.

![screenshot from 2017-06-11 17-22-25](https://user-images.githubusercontent.com/1042749/27010278-96194c3e-4eca-11e7-8e04-c45714d6d79e.png)

https://www.ag-grid.com/ng2-example/index.html?fromDocs=true&example=editor-component
https://plnkr.co/edit/259RDD?p=preview

**Comment by stuartshay** [comment]
Display 2 Grids in the Tab

Landmarks and Pluto are different grids

![grids](https://user-images.githubusercontent.com/887805/27013571-4c629782-4eb4-11e7-852e-bb0a883e0ad0.png)
