### ISSUE TITLE
LPC Report - Add PDF Link Open in New Window

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/CoreDataStore#77]
Designation Report: Label Change to Link to Download PDF Report 

![untitled](https://user-images.githubusercontent.com/887805/26947874-4a7a2ba0-4c62-11e7-8f9c-64623118a60c.png)

**Comment by stuartshay** [comment]
Need to Open in New Window to View PDF Report

**Comment by leduong** [comment]
done
