### ISSUE TITLE
Travis CI - Docker NodeJS Build 

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/CoreDataStore#78]
## NodeJS Docker Image Build

Docker Build - Use NodeJS/NG4 Artifacts Only 
Docker Hub:   stuartshay/coredatastore:node-release
Docker File:  node.dockerfile
Port: 3000
Docs : https://docs.travis-ci.com/user/docker/

- [X] 1 - Build & Deployment
- [X]  2 - Display Client Release Version 
- [x]  3 - After Git Checkout - Write to package.json 
XXX = Travis, CircleCI Build Number

![package](https://user-images.githubusercontent.com/887805/27365879-9a5869fe-5610-11e7-8bc0-026f425d2a1a.png)

## Sauce Labs/Selenium

Require Basic Functionality Tests, (Page Loads) 
- [x]  1 - PhantomJS/Headless Selenium Tests (Visual Test/ScreenShot Artifacts)  
- [ ]  2 - Run Docker Image and Run Tests on Docker Image
- [ ]  3 - Setup Sauce Labs

https://docs.travis-ci.com/user/sauce-connect/

**Comment by stuartshay** [comment]
Just want to have NodeJS/NG Assets 

Use this Docker File 
https://github.com/stuartshay/CoreDataStore/blob/master/docker/ui.dockerfile

**Comment by leduong** [comment]
![screenshot from 2017-06-25 03-53-33](https://user-images.githubusercontent.com/1042749/27511884-e8e9c2ec-5959-11e7-8fe8-a4a1793728d4.png)

**Comment by stuartshay** [comment]
This is Great, Lets go this week, I want to setup Browser and Mobile Mode

**Comment by leduong** [comment]
Give me some testcase on Mobile Mode

**Comment by stuartshay** [comment]
I will document issues, latter, the CSS for mobile and browser are different 
Need a Visual Test to see that Page Renders Correctly
