### ISSUE TITLE
Set Client ENV in Docker Compose  

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/CoreDataStore#81]
### Note: Branch Core2

Using this Image: (Runtime Built Local)
```
stuartshay/coredatastore:build 
```

![untitled](https://user-images.githubusercontent.com/887805/27513882-e043e816-5945-11e7-9867-44309df8e288.png)

Unable to set ENV in Docker Compose

Docker Compose File
https://github.com/stuartshay/CoreDataStore/blob/Core2/docker/docker-compose-staging.yml

```
environment:
 - NG_ENVIRONMENT=production   
 - LANDMARK=http://LANDMARK.API:80/api/
```

### Run Compose File
```
 docker-compose --file docker-compose-staging.yml  up
```

### Docker Image 
https://github.com/stuartshay/CoreDataStore/blob/Core2/docker/runtime.dockerfile

```
ENV NG_ENVIRONMENT ${NG_ENVIRONMENT}
```

**Comment by leduong** [comment]
It's build and bundle first, then only copy static file to build docker. Set ENV NG_ENVIRONMENT will not work... NG_ENVIRONMENT change value, it's need build again. Webstatic can't read ENV

**Comment by stuartshay** [comment]
When I use Docker Compose File and build image how can i set 

```
export NG_ENVIRONMENT=Dev
export LANDMARK=http://informationcart.eastus2.cloudapp.azure.com:80/api/
export MAPSAPI=http://informationcart.eastus2.cloudapp.azure.com:82/api/
```

**Comment by leduong** [comment]
If you build on the Docker Compose File, you need to copy the entire source to the docker and build it. Currently it is built then copied to the Docker image. The dock does not rebuild, therefore ENV in the docker file does not work

**Comment by stuartshay** [comment]
## Branch Core2

Docker Run Command 
https://stackoverflow.com/questions/30494050/how-do-i-pass-environment-variables-to-docker-containers

```
docker run --rm 
-e NG_ENVIRONMENT='staging' \ 
-e LANDMARK='http://informationcart.eastus2.cloudapp.azure.com:80/api/' \
-e MAPSAPI='http://informationcart.eastus2.cloudapp.azure.com:82/api/' \
--name coredatastore  -p 5000:5000  stuartshay/coredatastore
```
