### ISSUE TITLE
CircleCI - Postgres Testing

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/CoreDataStore#82]
Want to Run the Following Test in CircleCI 

- 1 Run Postgres Database Server  Docker Image 

```
docker pull stuartshay/coredatastore-postgres:stable
docker run --rm --name postgresdb -p 5432:5432  stuartshay/coredatastore-postgres:stable
```

- 2 Run Test Code

Test Code will connect to Database

```
test:
  override:    
- dotnet test test/CoreDataStore.Data.Postgre.Test/CoreDataStore.Data.Postgre.Test.csproj
```

**Comment by stuartshay** [comment]
The Image is being pulled but not run
Need to run the image and get the Database IP connection and change 

https://github.com/stuartshay/CoreDataStore/blob/master/test/CoreDataStore.Data.Postgre.Test/appsettings.json

Using Localhost

**Comment by leduong** [comment]
![screenshot from 2017-06-27 15-50-09](https://user-images.githubusercontent.com/1042749/27579049-5ddd7f9c-5b50-11e7-8bfb-9e6f7d684d77.png)
