### ISSUE TITLE
Travis Build - Client Build 

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/CoreDataStore#87]
- [x] 1 - Fix Swagger Link
https://api.coredatastore.com/swagger/ui/index.html

- [x] 3 - Reporting  API - Set using ENV 

Reports - https://report.coredatastore.com

Need to set using docker run
- [x] 4 - Fix Client Build Version String 

![untitled](https://user-images.githubusercontent.com/887805/28489111-59830660-6e88-11e7-8596-68ef98653895.png)

**Comment by stuartshay** [comment]
BootStrap.min,js

![untitled](https://user-images.githubusercontent.com/887805/28561442-7430c22a-70ec-11e7-9977-099e9ce8f9c0.png)

**Comment by leduong** [comment]
![screenshot from 2017-07-26 08-14-35](https://user-images.githubusercontent.com/1042749/28600182-874b3752-71da-11e7-83d6-ad59de2ea2cb.png)

**Comment by stuartshay** [comment]
Setting Report API Not Working
