### ISSUE TITLE
Travis Build

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/CoreDataStore#91]
- [ ] 1  Need to Split the Build Process -  (2 Workers Currently doing the same thing)

Worker 1 - Publish Docker Image to Docker Hub (No Sauce Labs Test)
Worker 2 - Sauce Labs Tests Only (No Publish)

- [ ] 2 - Restrict Build by Folder 
The Build Should only run when files are updated in Web Folder
(No Need to Run Tests when .NET Code is updated)

CoreDataStore.Web/

**Comment by leduong** [comment]
done
