### ISSUE TITLE
Travis Build Broken - Add Validation

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/CoreDataStore#93]
Current Travis Build is broken (Good Thing)

The NodeJS Build is failing and steps continue to Run, 

https://travis-ci.org/stuartshay/CoreDataStore

Any of these Steps Should Fail the build
- Build and Test 
- Create Docker Image 
- Docker Login Publish
- Rancher Deployment 

![untitled](https://user-images.githubusercontent.com/887805/29196963-f067c868-7e05-11e7-9b7c-a62f08697d5b.png)

Will Manually Add Image to Fix Current Site Status

![capture](https://user-images.githubusercontent.com/887805/29197101-fbdeea22-7e06-11e7-8baa-05d5b83ccb67.PNG)

**Comment by dmitryint** [comment]
https://github.com/travis-ci/travis-ci/issues/6072

**Comment by dmitryint** [comment]
Should be fixed. (The build now shows as failed)
