### ISSUE TITLE
NG Configuation 

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/CoreDataStore#94]
- [ ] 1 - Swagger Point to Landmark API

LANDMARK

![untitled](https://user-images.githubusercontent.com/887805/29241973-44c3af38-7f52-11e7-86a2-5583be6bfa23.png)

https://api.coredatastore.com/swagger/ui/index.html

Build Swagger Link 
 ```
LANDMARK=https://api.coredatastore.com/api/  

REMOVE api/ => https://api.coredatastore.com/
https://api.coredatastore.com/ + "swagger/ui/index.html"

Swagger Link = https://api.coredatastore.com/swagger/ui/index.html
```

**Comment by leduong** [comment]
explain more...

**Comment by stuartshay** [comment]
This Looks Good, Updated Description to Build Swagger Link
